name: Build GitHub Pages Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**.md"
      - "mkdocs.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Add local/bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Python dependencies
        run: |
          pipx install poetry
          poetry install --with docs --sync
      - name: Publish docs
        run: |
          poetry run mkdocs build --site-dir _site/
          ls -la _site/
      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: _site/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages